
export const GET_VACANCIES = 'GET_VACANCIES'
export const GET_INTERNSHIPS = 'GET_INTERNSHIPS'
export const GET_COMPANIES = 'GET_COMPANIES'
export const GET_UNIVERS = 'GET_UNIVERS'
export const GET_DEGREES = 'GET_DEGREES'
export const GET_JOB_AREAS = 'GET_JOB_AREAS'
export const GET_TECHNOS = 'GET_TECHNOS'

export const GET_STORIES = 'GET_STORIES'
export const GET_HACKATHONS = 'GET_HACKATHONS'
export const GET_STACKS = 'GET_STACKS'
export const GET_TESTS = 'GET_TESTS'

export const USER_SIGNUP = 'USER_SIGNUP'
export const USER_LOGIN = 'USER_LOGIN'
export const USER_LOGOUT = 'USER_LOGOUT'
export const ERROR_HANDLE = 'ERROR_HANDLE'

export const GET_USER_INFO = 'GET_USER_INFO'
export const ADD_USER_INFO = 'ADD_USER_INFO'
export const UPDATE_USER_INFO = 'UPDATE_USER_INFO'
export const GET_CV = 'GET_CV'
export const ADD_ROADMAP = 'ADD_ROADMAP'
export const GET_ROADMAP = 'GET_ROADMAP'