
export const GET_VACANCIES = 'GET_VACANCIES'
export const GET_INTERNSHIPS = 'GET_INTERNSHIPS'
export const GET_COMPANIES = 'GET_COMPANIES'

export const GET_STORIES = 'GET_STORIES'
export const GET_HACKATHONS = 'GET_HACKATHONS'
export const GET_STACKS = 'GET_STACKS'

export const USER_SIGNUP = 'USER_SIGNUP'
export const USER_LOGIN = 'USER_LOGIN'
export const USER_LOGOUT = 'USER_LOGOUT'
export const ERROR_HANDLE = 'ERROR_HANDLE'

export const GET_USER_INFO = 'GET_USER_INFO'