# Generated by Django 3.0.3 on 2020-05-03 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intenrships', to='items.Company'),
        ),
        migrations.AlterField(
            model_name='internship',
            name='job_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intenrships', to='items.JobArea'),
        ),
    ]
