# Generated by Django 3.0.3 on 2020-05-03 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20200503_0020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hunter',
            name='skills',
        ),
    ]
