# Generated by Django 3.0.3 on 2020-05-03 04:58

from django.db import migrations, models
import items.models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_auto_20200503_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hunter',
            name='thumbnailPath',
            field=models.ImageField(blank=True, null=True, upload_to=items.models.upload_user_photo),
        ),
    ]
